/******************************************
* Treehouse FSJS Techdegree:
* project 1 - A Random Quote Generator
* by Alex Giron
* March 2021
******************************************/

// --------------------------------------Quotes Array--------------------------------------------------

/*** 
* quote [type: string] - actual quote.
* source [type: string] - the person/character who said quote.
* citation [type: string] - reference to the source of the quote.
* year [type: number] - year quote originated.
* tags [type: string] - category of the quote i.e. humor, business, etc... EXTRA CREDIT: STEP 1
***/

const quotes = [ 
  {
   quote: 'A little knowledge is a dangerous thing',
   source: 'Alexander Pope',
   citation: 'An Essay on Criticism',
   year: 1709,
   tags: 'Business'
  }, 
  {
   quote: 'Not all those who wander are lost.',
   source: 'J.R.R. Tolkien',
   citation: 'The Fellowship of the Ring',
   year: 1954 
  }, 
  {
   quote: 'I am so clever that sometimes I don\'t understand a single word of what I am saying.',
   source: 'Oscar Wilde',
   citation: 'The Happy Prince and Other Stories',
   year: 1888,
   tags: 'Humor'
  }, 
  {
   quote: 'I love deadlines. I love the whooshing noise they make as they go by.',
   source: 'Douglas Adams',
   citation: 'The Salmon of Doubt',
   year: 2002
  }, 
  {
   quote: 'Time you enjoy wasting is not wasted time.',
   source: 'Marthe Troly-Curtin',
   citation: 'Phrynette Married',
   year: 1912,
   tags: 'Wisdom'
  }
];

// ------------------------------getRandomQuote Function------------------------------------------------

/*** 
  getRandomQuote function creates a random number, and uses that number to return a random quote object 
  from the quotes array.

  @param {[array]} arr - an array filled with object types.
  @returns {[object]} randomQuote - returns a random object quote from given array.
***/

function getRandomQuote( arr ) {
  // randomNumber is a random number generated from array's length. 
  const randomNumber = Math.floor( Math.random() *  arr.length );
  
  // randomQuote is a random quote object generated by the randomNumber variable.
  const randomQuote = arr[ randomNumber ];

  // returning the variable randomQuote
  return randomQuote;
}

// ------------------------------printQuote() function---------------------------------------------------

/*** 
  printQuote function will receieve the random quote from the getRandomQuote function and will 
  then display said quote properly in the browser.

  @param {[]} - No parameter in this function.
  @returns {[string]} message - Concatenated string.
***/

function printQuote(){

  /* quoteInfo is a const variable that stores the quote's Object properties + values 
  from the getRandomQuote function. */
  const quoteInfo = getRandomQuote(quotes);

  /* message is a string that will be used as the basis for printing the random quote*/
  let message = `
    <p class = 'quote'> ${ quoteInfo.quote } </p>
    <p class = 'source'> ${ quoteInfo.source } 
    `;

  /* Using two separate if statements to determine if the quote object has citation, year & tags properties, */
  if ( quoteInfo.citation !== undefined ) {
    message += `<span class = 'citation'> ${ quoteInfo.citation } </span>`
  }

  if ( quoteInfo.year !== undefined ) {
    message += `<span class = 'year'> ${ quoteInfo.year } </span>`
  }

  if ( quoteInfo.tags !== undefined ) {
    message += `<span class = 'tags'> , ${ quoteInfo.tags } </span>`
  }

  // Completed concatenated message string after if statements testing.
    message += `</p>`

  /* Code snippet provided by Treehouse. This syntax selects the 'quote-box' div and updates its HTML content
   with the random quote markup. */
  return document.getElementById('quote-box').innerHTML = message;

}

// -------------------------------randomRGB function---------------------------------------------------

/*** 
  randomRGB is a function that will return a random color using the RGB model.

  @param {[]} - No parameter in this function.
  @returns {[string]} randomRGBColor - string with the random rgb color definiton.
***/

function randomRGB() {

  let red = Math.floor( Math.random() * 256 );
  let green = Math.floor( Math.random() * 256);
  let blue = Math.floor ( Math.random() * 256);
  const randomRGBColor = `rgb( ${red}, ${green}, ${blue})`;

  return randomRGBColor;
}

// ------------------------------Extra Credit Steps 2 & 3----------------------------------------------

/* Referencing "Introduction to Events" by MDN Web Docs.
   URL: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events */

 // Creating a constant variable named button that will store reference to the button HTML element.
const button = document.querySelector('button');

// Setting button.onclick to an anonymous function that changes the background color of the HTML body element.
button.onclick = function(){
  document.querySelector('Body').style.backgroundColor = `${randomRGB()}`;
}

/* Referencing "Window setInterval() Method" by w3schools.com 
   URL: https://www.w3schools.com/jsref/met_win_setinterval.asp */

 // Setting the setInterval to change the random quote and background color every 10 seconds.
setInterval(function() { printQuote(); document.querySelector('Body').style.backgroundColor = `${randomRGB() }`;},10000);

/***
 * click event listener for the print quote button
 * DO NOT CHANGE THE CODE BELOW!!
***/

document.getElementById('load-quote').addEventListener("click", printQuote, false);